name="GANTA GNANESH"
resume_link=""
insta_link="https://www.instagram.com/gnanesh_9_9/"
git_link="https://github.com/GantaGnanesh2302/PROJECTS.git"
linkedin_link="https://www.linkedin.com/in/ganta-gnanesh-163a1823a?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app"
describe="Focused and enthusiastic developer with a keen interest in software development and artificial intelligence. By comprehensive exposure to the underlying concepts and applying them vividly to various projects, my love for these domains came into being. I am a passionate individual who thrives to build and apply algorithms to solve real-world industry problems."
birthday="23-02-2002"
phone="9392447451"
city="Guntur"
state="AP"
pincode="522112"
email_id="gnaneshganta@gmail.com"
interests=["coding","python","web","java","dsa","dbms"]
print('<!DOCTYPE html>')
print('<html lang="en">')
print('')
print('<head>')
print('')
print('  <!-- Google Tag Manager -->')
print('')
print('  <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({\'gtm.start\':')
print('  new Date().getTime(),event:\'gtm.js\'});var f=d.getElementsByTagName(s)[0],')
print('  j=d.createElement(s),dl=l!=\'dataLayer\'?\'&l=\'+l:\'\';j.async=true;j.src=')
print('  \'https://www.googletagmanager.com/gtm.js?id=\'+i+dl;f.parentNode.insertBefore(j,f);')
print('  })(window,document,\'script\',\'dataLayer\',\'GTM-5BB8W2X\');</script>')
print('  <!-- End Google Tag Manager -->')
print('  <link rel="icon" type="image/png" href="/favicon.png"/>')
print('  <meta charset="utf-8">')
print('  <meta content="width=device-width, initial-scale=1.0" name="viewport">')
print('')
print(f'  <title>{name}</title>')
print('  <meta content="" name="descriptison">')
print('  <meta content="" name="keywords">')
print('')
print('  <!-- Google Fonts -->')
print('')
print('  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">')
print('')
print('  <!-- Vendor CSS Files -->')
print('')
print('  <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">')
print('  <link href="assets/vendor/icofont/icofont.min.css" rel="stylesheet">')
print('  <link href="assets/vendor/remixicon/remixicon.css" rel="stylesheet">')
print('  <link href="assets/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">')
print('  <link href="assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">')
print('  <link href="assets/vendor/venobox/venobox.css" rel="stylesheet">')
print('')
print('  <!-- Template Main CSS File -->')
print('  ')
print('  <link href="assets/css/style.css" rel="stylesheet">')
print('')
print('')
print('  <!-- Global site tag (gtag.js) - Google Analytics -->')
print('  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-169007209-3"></script>')
print('  <script>')
print('    window.dataLayer = window.dataLayer || [];')
print('    function gtag(){dataLayer.push(arguments);}')
print("    gtag('js', new Date());")
print('')
print("    gtag('config', 'UA-169007209-3');")
print('  </script>')
print('  ')
print('')
print('')
print('')
print('  <!-- =======================================================')
print('  * Template Name: Personal - v2.1.0')
print('  * Template URL: https://bootstrapmade.com/personal-free-resume-bootstrap-template/')
print('  * Author: BootstrapMade.com')
print('  * License: https://bootstrapmade.com/license/')
print('  ======================================================== -->')
print('</head>')
print('')
print('<body>')
print('  ')
print('  <!-- Google Tag Manager (noscript) -->')
print('  <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5BB8W2X"')
print('  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>')
print('  <!-- End Google Tag Manager (noscript) -->')
print('  <!-- ======= Header ======= -->')
print('  ')
print('  <header id="header" class="header-tops">')
print('    <!-- <h1><span class="headd">Hi I am</span></h1> -->')
print('    <div class="container">')
print(f'      <h1><a href="index.html">{name}</a></h1>')
print('      <h2 style="color:#fff">I\'m <span class="typing" style="color:#12D640"></span></h2>')
print('      <nav class="nav-menu d-none d-lg-block">')
print('        <ul>')
print('          <li class="active"><a href="#header"> <span>Home</span></a></li>')
print('          <li><a href="#about"><span>About</span></a></li>')
print('          <li><a href="#education"> <span>Education</span></a></li>')
print('          <!-- <li><a href="#experience"> <span>Experience</span></a></li> -->')
print('<!--          <li><a href="#projects"> <span>Projects</span></a></li>-->')
print('          <li><a href="#portfolio"> <span>Projects</span></a></li>')
print('          <li><a href="https://zenodo.org/records/10938228"> <span>Publications</span></a></li>')
print('          <li><a href="#skills"> <span>Skills</span></a></li>')
print('          <!-- to change resume -->')
print(f'          <li><a href="{resume_link}" target="_blank"> <span>Resume</span></a></li>')
print('          <!-- <li><a href="#links"> <span>Resume & Links</span></a></li> -->')
print('          <li><a href="#contacts"> <span>Contact</span></a></li>')
print('')
print('        </ul>')
print('      </nav><!-- .nav-menu -->')
print('<div class="social-links">')
print(f'  <a href="{linkedin_link}" target="_blank" class="linkedin"><i class="bx bxl-linkedin"></i></a>')
print(f'  <a href="{git_link}" target="_blank" class="github"><i class="bx bxl-github"></i></a>')
print(f'  <a href="{insta_link}" target="_blank" class="instagram"><i class="bx bxl-instagram"></i></a>')
print('</div>')
print('<div class="social-links">')
print('  <style>')
print('    .blink{')
print('      animation: blink 1s linear infinite;')
print('      color: red;')
print('    }')
print('    @keyframes blink{')
print('      50%{')
print('        opacity: 0;')
print('      }')
print('    }')
print('  </style>')
print('  <h3 class="blink"><b><u>Announcements</u></b></h3>')
print('</div>')
print('<div class="social-links">')
print('  <meta name="viewport" content="width=device-width, initial-scale=1">')
print('  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">')
print('  <li>Wants to build your resume  <a href="https://forms.gle/6RvAZqPQgKpKHPwm7"><i class="fa">&#xf08e;</i></a><br></li>')
print('</div>')
print('<div class="social-links">')
print('  <li>Wants to develop a website <a href="https://forms.gle/6RvAZqPQgKpKHPwm7"><i class="fa">&#xf08e;</i></a></li>')
print('</div>')
print('<div class="social-links">')
print('  <li>Wants to build your personal domain  <a href="https://forms.gle/6RvAZqPQgKpKHPwm7"><i class="fa">&#xf08e;"></i></a></li>')
print('</div>')
print('</div>')
print('')
print('</header><!-- End Header -->')
print('')
print('<!-- ======= About Section ======= -->')
print('<section id="about" class="about">')
print('')
print('  <!-- ======= About Me ======= -->')
print('  <div class="about-me container">')
print('')
print('    <div class="section-title">')
print('      <h2>About</h2>')
print('    </div>')
print('')
print('    <div class="row">')
print('      <div class="col-lg-4" data-aos="fade-right">')
print('        <img src="assets/img/WhatsApp Image 2023-01-07 at 11.35.33.jpg" class="img-fluid" alt="">')
print('      </div>')
print('      <div class="col-lg-8 pt-4 pt-lg-0 content" data-aos="fade-left">')
print(f'        <p>{describe}</p>')
print('        <div class="row">')
print('          <div class="col-lg-6">')
print('            <ul>')
print(f'              <li><i class="icofont-rounded-right"></i> <strong>Birthday:</strong>{birthday}</li>')
print(f'              <li><i class="icofont-rounded-right"></i> <strong>Phone:</strong> +91 {phone}</li>')
print('            </ul>')
print('          </div>')
print('          <div class="col-lg-6">')
print('            <ul>')
print(f'              <li><i class="icofont-rounded-right"></i> <strong>City:</strong>{city},{state},{pincode}</li>')
print(f'              <li><i class="icofont-rounded-right"></i> <strong>Email:</strong>{email_id}</li>')
print('            </ul>')
print('          </div>')
print('        </div>')
print('      </div>')
print('    </div>')
print('')
print('  </div><!-- End About Me -->')
print('<!-- ======= Interests ======= -->')
print('<div class="interests container">')
print('  <div class="section-title">')
print('    <h2>Interests</h2>')
print('  </div>')
print('  <div class="row">')
print('    <div class="col-lg-3 col-md-4">')
print('      <div class="icon-box">')
print('        <i class="ri-global-line" style="color: #ffbb2c;"></i>')
print(f'        <h3>{interests[0]}</h3>')
print('      </div>')
print('    </div>')
print('    <div class="col-lg-3 col-md-4 mt-4 mt-md-0">')
print('      <div class="icon-box">')
print('        <i class="ri-database-2-line" style="color: #5578ff;"></i>')
print(f'        <h3>{interests[1]}</h3>')
print('      </div>')
print('    </div>')
print('    <div class="col-lg-3 col-md-4 mt-4 mt-md-0">')
print('      <div class="icon-box">')
print('        <i class="ri-camera-3-line" style="color: #e80368;"></i>')
print(f'        <h3>{interests[2]}</h3>')
print('      </div>')
print('    </div>')
print('    <div class="col-lg-3 col-md-4 mt-4 mt-lg-0">')
print('      <div class="icon-box">')
print('        <i class="ri-english-input" style="color: #1c7d32;"></i>')
print(f'        <h3>{interests[3]}</h3>')
print('      </div>')
print('    </div>')
print('    <div class="col-lg-3 col-md-4 mt-4">')
print('      <div class="icon-box">')
print('        <i class="ri-bar-chart-box-line" style="color: #105ee6;"></i>')
print(f'        <h3>{interests[4]}</h3>')
print('      </div>')
print('    </div>')
print('    <div class="col-lg-3 col-md-4 mt-4">')
print('      <div class="icon-box">')
print('        <i class="ri-file-list-3-line" style="color: #47aeff;"></i>')
print(f'        <h3>{interests[5]}</h3>')
print('      </div>')
print('    </div>')
print('  </div>')
print('</div><!-- End Interests -->')
print('</section><!-- End About Section -->')
print('<!-- ======= Education Section ======= -->')
print('<section id="education" class="services">')
print('  <div class="container">')
print('    <div class="section-title">')
print('      <h2>Education</h2>')
print('    </div>')
print('    <div class="row">')
print('      <div class="col-lg-12" data-aos="fade-up" style="display: inline-block;">')
print('        <div class="col-md-4 mt-4 mt-md-0 icon-box" data-aos="fade-up" data-aos-delay="100" style="padding:0px 0px;padding-bottom: 5px;display: inline-block;">')
print('          <img src="assets/img/education/clg1.png" class="img-fluid" alt="">')
print('          <p style="text-align:left;color:#fff;padding: 5px 10px;"><em>B.Tech. in Information Technology</em></p>')
print('          <h5 style="text-align:left;padding: 0px 10px;">June 2020 - May 2024</h5>')
print('          <h6 style="text-align:left;color:#fff;padding: 0px 10px;">Relevant Coursework</h6>')
print('          <ul style="text-align:left;color:#fff;">')
print('            <li>Information Technology</li>')
print('            <li>Python development</li>')
print('            <li>Machine Learning</li>')
print('          </ul>')
print('        </div>')
print('        <div class="col-md-4 mt-4 mt-md-0 icon-box" data-aos="fade-up" data-aos-delay="100" style="padding:0px 0px;padding-bottom: 5px;display: inline-block;">')
print('          <img src="assets/img/education/narayanaclg.png" class="img-fluid" alt="">')
print('          <p style="text-align:left;color:#fff;padding: 5px 10px;"><em>Intermediate in MPC Course</em></p>')
print('          <h5 style="text-align:left;padding: 0px 10px;">June 2018- April 2020</h5>')
print('          <h6 style="text-align:left;color:#fff;padding: 0px 10px;">Relevant Coursework</h6>')
print('          <ul style="text-align:left;color:#fff;">')
print('            <li>Mathematics</li>')
print('            <li>English (First language)</li>')
print('            <li>IIT Training</li>')
print('          </ul>')
print('        </div>')
print('        <div class="col-md-4 mt-4 mt-md-0 icon-box" data-aos="fade-up" data-aos-delay="100" style="padding:0px 0px;padding-bottom: 5px;display: inline-block;">')
print('          <img src="assets/img/education/scts.jpg" class="img-fluid" alt="">')
print('          <p style="text-align:left;color:#fff;padding: 5px 10px;"><em>Primary Studies</em></p>')
print('          <h5 style="text-align:left;padding: 0px 10px;">June 2006- May 2018</h5>')
print('          <h6 style="text-align:left;color:#fff;padding: 0px 10px;">Relevant Coursework</h6>')
print('          <ul style="text-align:left;color:#fff;">')
print('            <li>Mathematics</li>')
print('            <li>English (First language)</li>')
print('            <li>Remaining Standard Subjects</li>')
print('          </ul>')
print('        </div>')
print('      </div>')
print('    </div>')
print('  </div>')
print('<div class="portfolio">')
print('    <div class="container">')
print('      <div class="section-title">')
print('        <h2>Online Certification</h2>')
print('      </div>')
print('')
print('      <div class="row portfolio-container" style="position: relative; height: 437.75px;">')
print('')
print('        <div class="col-lg-4 col-md-6 portfolio-item filter-app" style="position: absolute; left: 0px; top: 0px;">')
print('          <div class="portfolio-wrap">')
print('            <img src="assets/img/certification/cognibot.png" class="img-fluid" alt="">')
print('            <div class="portfolio-info">')
print('              <h4>Baseline:Data,ML</h4>')
print('              <div class="portfolio-links">')
print('                <a href="https://www.cloudskillsboost.google/public_profiles/ace87a72-6330-430d-96ee-e3366939a0fc" target="_blank" title="Certificate"><i class="bx bx-link"></i></a>')
print('              </div>')
print('            </div>')
print('          </div>')
print('        </div>')
print('')
print('        <div class="col-lg-4 col-md-6 portfolio-item filter-app" style="position: absolute; left: 370px; top: 0px;">')
print('          <div class="portfolio-wrap">')
print('            <img src="assets/img/certification/nareshit.png" class="img-fluid" alt="">')
print('            <div class="portfolio-info">')
print('              <h4>Eduskills</h4>')
print('              <div class="portfolio-links">')
print('                <a href="https://drive.google.com/file/d/1RSRwds6aXoyfuCOvCED2NMJMXpc_-2de/view?usp=drivesdk" target="_blank" title="Certificate"><i class="bx bx-link"></i></a>')
print('              </div>')
print('            </div>')
print('          </div>')
print('        </div>')
print('')
print('        <div class="col-lg-4 col-md-6 portfolio-item filter-app" style="position: absolute; left: 740px; top: 0px;">')
print('          <div class="portfolio-wrap">')
print('            <img src="assets/img/certification/eduonix.png" class="img-fluid" alt="">')
print('            <div class="portfolio-info">')
print('              <h4>Deep Learning</h4>')
print('              <div class="portfolio-links">')
print('                <a href="https://drive.google.com/file/d/1RiZv9zHfP8z4NyIIQbJYnUS5d4JhcGGR/view?usp=drivesdk" target="_blank" title="Certificate"><i class="bx bx-link"></i></a>')
print('              </div>')
print('            </div>')
print('          </div>')
print('        </div>')
print('')
print('        <div class="col-lg-4 col-md-6 portfolio-item filter-project" style="position: absolute; left: 0px; top: 218.875px;">')
print('          <div class="portfolio-wrap">')
print('            <img src="assets/img/certification/SkillUp_Logo.jpg" class="img-fluid" alt="">')
print('            <div class="portfolio-info">')
print('              <h4>Publication</h4>')
print('              <div class="portfolio-links">')
print('                <a href="https://drive.google.com/file/d/1Rj04HT0fm9Mt37u2gMe8KCZD24QECKCx/view?usp=drivesdk" target="_blank" title="Certificate"><i class="bx bx-link"></i></a>')
print('              </div>')
print('            </div>')
print('          </div>')
print('        </div>')
print('')
print('        <div class="col-lg-4 col-md-6 portfolio-item filter-project" style="position: absolute; left: 370px; top: 218.875px;">')
print('          <div class="portfolio-wrap">')
print('            <img src="assets/img/certification/algox.png" class="img-fluid" alt="">')
print('            <div class="portfolio-info">')
print('              <h4>Python</h4>')
print('              <div class="portfolio-links">')
print('                <a href="https://www.hackerrank.com/certificates/6c63b1e4462e" target="_blank" title="Certificate"><i class="bx bx-link"></i></a>')
print('              </div>')
print('            </div>')
print('          </div>')
print('        </div>')
print('  </section>')
print("<!-- Start Project Section -->")
print('<section id="portfolio" class="portfolio">')
print('  <div class="container">')
print('')
print('    <div class="section-title">')
print('      <h2>Projects</h2>')
print('    </div>')
print('')
print('    <div class="row">')
print('      <div class="col-lg-12 d-flex justify-content-center">')
print('        <ul id="portfolio-flters">')
print('          <li data-filter="*" class="filter-active">All</li>')
print('          <li data-filter=".filter-app">Project</li>')
print('        </ul>')
print('      </div>')
print('    </div>')
print('')
print('    <div class="row portfolio-container">')
print('')
print('      <div class="col-lg-4 col-md-6 portfolio-item filter-app">')
print('        <center><h4>House_Price_Prediction</h4></center>')
print('        <div class="portfolio-wrap">')
print('          <img src="assets/img/project/attendance.jpg" class="img-fluid" alt="">')
print('          <div class="portfolio-info">')
print('            ')
print('            <div class="portfolio-links">')
print('              <a href="projects/face_recognization.html" data-gall="portfolioDetailsGallery" data-vbtype="iframe" class="venobox" title="Project Details"><i class="bx bx-info-circle"></i></a>')
print('            </div>')
print('          </div>')
print('        </div>')
print('      </div>')
print('')
print('      <div class="col-lg-4 col-md-6 portfolio-item filter-app">')
print('        <center>')
print('          <h4>Car_service_Price_Prediction</h4>')
print('        </center>')
print('        <div class="portfolio-wrap">')
print('          <img src="assets/img/project/loan.jpg" class="img-fluid" alt="">')
print('          <div class="portfolio-info">')
print('            <div class="portfolio-links">')
print('              <a href="projects/loan.html" data-gall="portfolioDetailsGallery" data-vbtype="iframe" class="venobox" title="Project Details"><i class="bx bx-info-circle"></i></a>')
print('            </div>')
print('          </div>')
print('        </div>')
print('      </div>')
print('')
print('      <div class="col-lg-4 col-md-6 portfolio-item filter-app">')
print('        <center><h4>Style Transfer</h4></center>')
print('        <div class="portfolio-wrap">')
print('          <img src="assets/img/project/snake.jpg" class="img-fluid" alt="">')
print('          <div class="portfolio-info">')
print('            ')
print('            <div class="portfolio-links">')
print('              <a href="projects/Live snake game.html" data-gall="portfolioDetailsGallery" data-vbtype="iframe" class="venobox" title="Project Details"><i class="bx bx-info-circle"></i></a>')
print('            </div>')
print('          </div>')
print('        </div>')
print('      </div>')
print('')
print('      <div class="col-lg-4 col-md-6 portfolio-item filter-app">')
print('        <br>')
print('        <center><h4>My Portfolio</h4></center>')
print('        <div class="portfolio-wrap">')
print('          <img src="assets/img/project/blog.jpg" class="img-fluid" alt="">')
print('          <div class="portfolio-info">')
print('            ')
print('            <div class="portfolio-links">')
print('              <a href="projects/blog.html" data-gall="portfolioDetailsGallery" data-vbtype="iframe" class="venobox" title="Project Details"><i class="bx bx-info-circle"></i></a>')
print('            </div>')
print('          </div>')
print('        </div>')
print('      </div>')
print('    </div>')
print('')
print('  </div>')
print('</section>')
print('')
print('<!-- End Project Section -->')
print("<!-- Start Skills Section -->")
print('')
print('<section id="skills" class="services">')
print('  <div class="container">')
print('    <div class="section-title">')
print('      <h2>Skills</h2>')
print('    </div>')
print('    <div class="row">')
print('      <div class="col-lg-12" data-aos="fade-up">')
print('        <div class="col-md-12 mt-4 mt-md-0 icon-box" data-aos="fade-up" data-aos-delay="100" style="background:#fff">')
print('          <h4 style="text-align:left;color:#09203a">Languages and Databases</h4>')
print('          <p style="text-align:left;">')
print('            <img src="https://www.vectorlogo.zone/logos/python/python-horizontal.svg" alt="vectorlogo.zone" height="50" width="150">')
print('            <img src="https://www.vectorlogo.zone/logos/java/java-horizontal.svg" alt="vectorlogo.zone" height="50" width="120">')
print('            <img src="https://www.vectorlogo.zone/logos/w3_html5/w3_html5-ar21.svg" alt="vectorlogo.zone">')
print('            <img src="https://upload.wikimedia.org/wikipedia/commons/d/d5/CSS3_logo_and_wordmark.svg" alt="upload.wikimedia.org" height="60" width="90">')
print('            <img src="assets/img/javascript-ar21.svg" alt="javascript logo.zone" height="100" width="190">')
print('            <img src="https://www.vectorlogo.zone/logos/mysql/mysql-horizontal.svg" alt="vectorlogo.zone" height="70" width="130">')
print('          </p>')
print('        </div>')
print('        <div class="col-md-12 mt-4 mt-md-0 icon-box" data-aos="lefade-up" data-aos-delay="100" style="background:#fff">')
print('          <h4 style="text-align:left;color:#09203a">Frameworks</h4>')
print('          <p style="text-align:left;">')
print('            <img src="" alt="" srcset="">')
print('            <img src="https://www.vectorlogo.zone/logos/pocoo_flask/pocoo_flask-ar21.svg" alt="vectorlogo.zone">')
print('            <img src="https://www.vectorlogo.zone/logos/djangoproject/djangoproject-ar21.svg" alt="vectorlogo.zone">')
print('            <img src="https://www.vectorlogo.zone/logos/reactjs/reactjs-ar21.svg" alt="vectorlogo.zone">')
print('            <!-- <img src="https://www.vectorlogo.zone/logos/getbootstrap/getbootstrap-ar21.svg" alt="vectorlogo.zone"> -->')
print('            <!--<img src="https://www.vectorlogo.zone/logos/tensorflow/tensorflow-ar21.svg" alt="vectorlogo.zone"> -->')
print('            <img src="https://www.vectorlogo.zone/logos/numpy/numpy-ar21.svg" alt="numpy logo" srcset="" height="70" width="160">')
print('            <img src="https://www.vectorlogo.zone/logos/usepanda/usepanda-ar21.svg" alt="pandas logo" srcset="" height="70" width="120">')
print('            <!-- <img src="https://www.vectorlogo.zone/logos/pytorch/pytorch-ar21.svg" alt="vectorlogo.zone"> -->')
print('            <img src="assets/img/matplotlib.jpeg" alt="matplotlib logo" srcset="" height="90" width="120">')
print('          </p>')
print('        </div>')
print('        <div class="col-md-12 mt-4 mt-md-0 icon-box" data-aos="lefade-up" data-aos-delay="100" style="background:#fff">')
print('          <h4 style="text-align:left;color:#09203a">Tools</h4>')
print('          <p style="text-align:left;">')
print('            <img src="https://www.vectorlogo.zone/logos/github/github-ar21.svg" alt="vectorlogo.zone">')
print('            <!-- <img src="https://www.vectorlogo.zone/logos/amazon_aws/amazon_aws-ar21.svg" alt="vectorlogo.zone"> -->')
print('            <img src="https://www.vectorlogo.zone/logos/google_cloud/google_cloud-ar21.svg" alt="vectorlogo.zone">')
print('            <img src="https://www.vectorlogo.zone/logos/heroku/heroku-ar21.svg" alt="vectorlogo.zone">')
print('            <img src="https://www.vectorlogo.zone/logos/jupyter/jupyter-ar21.svg" alt="vectorlogo.zone">')
print('            <img src="assets/img/vscode2.png" alt="vscode logo" srcset="" width="190" height="60">')
print('          </p>')
print('        </div>')
print('      </div>')
print('    </div>')
print('  </div>')
print('</section>')
print('')
print('<!-- End Skills Section -->')
print("<!-- Start Links section -->")
print('')
print('<section id="links" class="services">')
print('  <div class="container">')
print('    <div class="section-title">')
print('      <h2>Resume & Links</h2>')
print('    </div>')
print('    <div class="row">')
print('      <div class="col-md-3 mt-4 mt-md-0 icon-box" data-aos="fade-up" data-aos-delay="100">')
print('        <a href="https://drive.google.com/file/d/1WRBBjSYTJqpbpoFpRN7mH7HZ9MvEnG8j/view?usp=drivesdk" target="_blank"><div class="icon"><i class="icofont-page"></i></div></a>')
print('        <h4 class="title"><a href="https://drive.google.com/file/d/1WRBBjSYTJqpbpoFpRN7mH7HZ9MvEnG8j/view?usp=drivesdk" target="_blank">Resume</a></h4>')
print('        <p class="description" style="color:#fff;">The link contains downloadable resume</p>')
print('      </div>')
print('      <!-- <div class="col-md-3 mt-4 mt-md-0 icon-box" data-aos="fade-up">')
print('        <a href="https://github.com/rajaprerak/LeetCode_Problems" target="_blank"><div class="icon"><i class="icofont-link"></i></div></a>')
print('        <h4 class="title"><a href="https://github.com/rajaprerak/LeetCode_Problems" target="_blank">LeetCode Repository</a></h4>')
print('        <p class="description" style="color:#fff;"> The github repository contains leetcode problems solution in python.</p>')
print('      </div> -->')
print('      <!-- <div class="col-md-3 mt-4 mt-md-0 icon-box" data-aos="fade-up" data-aos-delay="100">')
print('        <a href="https://techingenious.herokuapp.com/" target="_blank"><div class="icon"><i class="icofont-page"></i></div></a>')
print('        <h4 class="title"><a href="https://techingenious.herokuapp.com/" target="_blank">Blog</a></h4>')
print('        <p class="description" style="color:#fff;">Blog containing articles on AI, coding, development</p>')
print('      </div> -->')
print('    </div>')
print('  </div>')
print('</section>')
print('')
print('<!-- End Links Section -->')
print("<!-- Start Contact Section -->")
print('')
print('<section id="contacts" class="contact">')
print('  <div class="container">')
print('')
print('    <div class="section-title">')
print('      <h2>Contact</h2>')
print('    </div>')
print('')
print('    <div class="row mt-2">')
print('')
print('      <div class="col-md-6 d-flex align-items-stretch">')
print('        <div class="info-box">')
print('          <i class="bx bx-map"></i>')
print('          <h3>My Address</h3>')
print('          <p>Kondapaturu-522112</p>')
print('          <p>Guntur</p>')
print('          <p>AndhraPradesh</p>')
print('        </div>')
print('      </div>')
print('')
print('      <div class="col-md-6 mt-4 mt-md-0 d-flex align-items-stretch">')
print('        <div class="info-box">')
print('          <i class="bx bx-share-alt"></i>')
print('          <h3>Social Profiles</h3>')
print('          <div class="social-links">')
print('            <a href="https://www.linkedin.com/in/ganta-gnanesh-163a1823a?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app" target="_blank" class="linkedin"><i class="bx bxl-linkedin"></i></a>')
print('            <a href="mailto:gnaneshganta@gmail.com" target="_blank" class="google"><i class="bx bxl-google"></i></a>')
print('            <a href="https://www.instagram.com/gnanesh_9_9/" target="_blank" class="instagram"><i class="bx bxl-instagram"></i></a>')
print('')
print('          </div>')
print('        </div>')
print('      </div>')
print('')
print('      <div class="col-md-6 mt-4 d-flex align-items-stretch">')
print('        <div class="info-box">')
print('          <i class="bx bx-envelope"></i>')
print('          <h3>Email</h3>')
print('          <p>gnaneshganta@gmail.com</p>')
print('          <p>gnaneshganta2002@gmail.com</p>')
print('        </div>')
print('      </div>')
print('      <div class="col-md-6 mt-4 d-flex align-items-stretch">')
print('        <div class="info-box">')
print('          <i class="bx bx-phone-call"></i>')
print('          <h3>Contact</h3>')
print('          <p>+91 9392447451</p>')
print('        </div>')
print('      </div>')
print('    </div>')
print('    <!-- <div id="sfczmlqxr5caww28rswrt8849ghbekgnh3j" ></div><script type="text/javascript" src="https://counter1.stat.ovh/private/counter.js?c=zmlqxr5caww28rswrt8849ghbekgnh3j&down=async" async></script><noscript><a href="https://www.freecounterstat.com" title="free web counter"><img src="https://counter1.stat.ovh/private/freecounterstat.php?c=zmlqxr5caww28rswrt8849ghbekgnh3j" border="0" title="free web counter" alt="free web counter" style="visibility: none;"></a></noscript> -->')
print('  </div>')
print('</section>')
print('')
print('<!-- End Contact Section -->')
print('<footer id="footer" class="footer dark-background">')
print('    <div class="container">')
print('      <h3 class="sitename">Personal</h3>')
print('      <div class="social-links d-flex justify-content-center">')
print('        <a href=""><i class="bi bi-twitter-x"></i></a>')
print('        <a href=""><i class="bi bi-facebook"></i></a>')
print('        <a href=""><i class="bi bi-instagram"></i></a>')
print('        <a href=""><i class="bi bi-skype"></i></a>')
print('        <a href=""><i class="bi bi-linkedin"></i></a>')
print('      </div>')
print('      <div class="container">')
print('        <div class="copyright">')
print('          <span>Copyright</span> <strong class="px-1 sitename">Personal</strong> <span>All Rights Reserved</span>')
print('        </div>')
print('        <div class="credits">')
print('          <!-- All the links in the footer should remain intact. -->')
print('          <!-- You can delete the links only if you\'ve purchased the pro version. -->')
print('          <!-- Licensing information: https://bootstrapmade.com/license/ -->')
print('          <!-- Purchase the pro version with working PHP/AJAX contact form: [buy-url] -->')
print('          <span>© Copyright</span> <strong class="px-1 sitename">Personal</strong> <span>All Rights Reserved</span>')
print('          by <a href="https://gantagnanesh.com">Ganta Gnanesh</a>')
print('        </div>')
print('      </div>')
print('    </div>')
print('  </footer>')
print('')
print('<!-- Vendor JS Files -->')
print('  <script src="assets/vendor/jquery/jquery.min.js"></script>')
print('  <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>')
print('  <script src="assets/vendor/jquery.easing/jquery.easing.min.js"></script>')
print('  <script src="assets/vendor/php-email-form/validate.js"></script>')
print('  <script src="assets/vendor/waypoints/jquery.waypoints.min.js"></script>')
print('  <script src="assets/vendor/counterup/counterup.min.js"></script>')
print('  <script src="assets/vendor/owl.carousel/owl.carousel.min.js"></script>')
print('  <script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>')
print('  <script src="assets/vendor/venobox/venobox.min.js"></script>')
print('  <script src="assets/vendor/typed.js/typed.min.js"></script>')
print('  <script type="text/javascript">')
print('    var typed = new Typed(\'.typing\',{')
print('      strings: ["Python Developer","Data Analyst","Sql Analyst"],')
print('      loop: true,')
print('      typeSpeed: 65,')
print('      backSpeed: 65')
print('    });')
print('  </script>')
print('')
print('<!-- Template Main JS File -->')
print('  <script src="assets/js/main.js"></script>')
print('')
print('</body>')
print('')
print('</html>')





